defaults: &defaults
  adapter: mysql
  database: madet_git
  username: root
  password: admin
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults